name: Generate PDF

on:
  workflow_dispatch:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince-15-linux-generic-x86_64.tar.gz -O
          tar zxf prince-15-linux-generic-x86_64.tar.gz
          cd prince-15-linux-generic-x86_64
          yes "" | sudo ./install.sh
      - name: Generate PDF
        run: npx docusaurus-prince-pdf -u https://nasa-ammos.github.io/aerie-docs/introduction/ --output pdf/aerie-docs.pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: docs-pdf
          path: pdf/aerie-docs.pdf
          if-no-files-found: error
