name: Generate PDFs

on:
  workflow_dispatch:

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install Prince
        run: |
          curl https://www.princexml.com/download/prince-15-linux-generic-x86_64.tar.gz -O
          tar zxf prince-15-linux-generic-x86_64.tar.gz
          cd prince-15-linux-generic-x86_64
          yes "" | sudo ./install.sh
      - name: Generate PDFs
        run: sh ./generate-pdfs/generate-pdfs.sh
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: aerie-docs
          path: pdf
          if-no-files-found: error
